// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyeonagvnipzxpvcquag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5ZW9uYWd2bmlwenhwdmNxdWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDgxNjgsImV4cCI6MjA2MTI4NDE2OH0.P3C2WVWUjLGIb-PHznjjtm70XZenVvj6lt9oVk0NUP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);